services:
  zkt-gateway:
    image: valentas/zkt-access-gateway:1.0
    platform: linux/amd64
    container_name: zkt-gateway
    restart: unless-stopped
    # ports:
    #   - "8000:8000"
    environment:
      - ZKT_CONNSTR=protocol=TCP,ipaddress=192.168.1.7,port=4370,timeout=4000,passwd=
      - MQTT_BROKER=
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PASSWORD=
      # - TZ=Europe/Vilnius
      # - ZK_DEBUG=false
      # - ZK_BRIDGE_TIMEOUT=60
      # - ZK_SYNC_INTERVAL=60
      # - ZK_FULL_SYNC_INTERVAL=600
    # volumes:
    #   - ./data:/app/data
